# Generated by Django 3.2 on 2023-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_id_verifylogin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifylogin',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
